------------------------------------------------------------------------

-- Garrysmod fastDL resources.lua file generated by ConfigCreator.com --

------------------------------------------------------------------------

-- Workshop Items (3795332775) --

resource.AddWorkshop( '1974924803' ) -- [ Star Wars ] Expanded Universe Misc Vehicles Pack [ Over 100 vehicles! ]
resource.AddWorkshop( '3333631784' ) -- [ArcCW | SW] Kraken's Effects & Resources
resource.AddWorkshop( '2131057232' ) -- [ArcCW] Arctic's Customizable Weapons (Base)
resource.AddWorkshop( '3293413870' ) -- [ArcCW] Kraken's Empire Essentials - Content
resource.AddWorkshop( '3318137355' ) -- [ArcCW] Kraken's Explosive Expansion - Content
resource.AddWorkshop( '3407248011' ) -- [ArcCW] Kraken's Republic Essentials - Content
resource.AddWorkshop( '3386299353' ) -- [ArcCW] Kraken's Special Forces - Content
resource.AddWorkshop( '3029982717' ) -- [DrGBase] Star Wars Rebel NPCs
resource.AddWorkshop( '2521732828' ) -- [IN] Imperial Inquisitors
resource.AddWorkshop( '2912816023' ) -- [LVS] - Framework
resource.AddWorkshop( '3712852779' ) -- [LVS] - Missiles Overhaul
resource.AddWorkshop( '2912826012' ) -- [LVS] - Planes - Pack
resource.AddWorkshop( '2919757295' ) -- [LVS] - Star Wars - Pack
resource.AddWorkshop( '3623375941' ) -- [LVS] 2-H Modular Repulsortank
resource.AddWorkshop( '3623388047' ) -- [LVS] 2-H Repulsor Skinpack (OPTIONAL)
resource.AddWorkshop( '3033052046' ) -- [LVS] AT-ST
resource.AddWorkshop( '3731685154' ) -- [LVS] Essential TIEs to Warfare FULL Pack
resource.AddWorkshop( '3238211247' ) -- [LVS] LAAT/i Gunship (Atmospheric & Space)
resource.AddWorkshop( '3026288054' ) -- [LVS] LAAT/le Patrol Gunship
resource.AddWorkshop( '3006666425' ) -- [LVS] NU-Class Attack Shuttle
resource.AddWorkshop( '3589265787' ) -- [LVS] Star Wars Imperial Troop Transporter | Andor
resource.AddWorkshop( '3391394245' ) -- [LVS] SW Vehicles: Imperial Shuttles [Reupload]
resource.AddWorkshop( '3391400544' ) -- [LVS] SW Vehicles: Rebel Essentials [Reupload]
resource.AddWorkshop( '3391389678' ) -- [LVS] SW Vehicles: TIE Essentials [Reupload]
resource.AddWorkshop( '3391390740' ) -- [LVS] SW Vehicles: TIE Experimentals [Reupload]
resource.AddWorkshop( '2946953634' ) -- [LVS] TIE Fighters Expanded
resource.AddWorkshop( '3591373894' ) -- [LVS] TIE Mauler
resource.AddWorkshop( '3677632308' ) -- [LVS] Warhound Attack Tank
resource.AddWorkshop( '1827305571' ) -- [MA2] StarWars BX VibroSword
resource.AddWorkshop( '2816230161' ) -- [NCS] Defcon System
resource.AddWorkshop( '3015660769' ) -- [NCS] Shared Resources
resource.AddWorkshop( '3212776416' ) -- [NCS] Transport Content (Content)
resource.AddWorkshop( '1268434165' ) -- [NGRP] Rebel Pilot Helmet Prop
resource.AddWorkshop( '1268173091' ) -- [NGRP] Rebel Pilot Variant Playermodel
resource.AddWorkshop( '104482086' ) -- [Official] Precision Tool
resource.AddWorkshop( '2532255253' ) -- [RDV] Communications (Content)
resource.AddWorkshop( '2696785946' ) -- [RDV] Library (v2)
resource.AddWorkshop( '2086586201' ) -- [RDV] No-Target Tool
resource.AddWorkshop( '889827473' ) -- [TFA Official] Star Wars Shared Resources [ Sounds, Icons, Shared Support Menu ]
resource.AddWorkshop( '1264664679' ) -- [TFA] Battlefront 2017 - CIS Weapons (Legacy)
resource.AddWorkshop( '1264669772' ) -- [TFA] Battlefront 2017 - CIS Weapons Content (Legacy)
resource.AddWorkshop( '1705500509' ) -- [TFA] StarWars CIS Weapon Reworked Pack
resource.AddWorkshop( '2019568291' ) -- [TFA] StarWars Reworked Grenade Pack
resource.AddWorkshop( '1741985166' ) -- [TFA] StarWars Reworked Shared Resources and Assets
resource.AddWorkshop( '2186403956' ) -- [TFA] StarWars WristBlasters Pack
resource.AddWorkshop( '1102570708' ) -- [wOS] Advanced Lightsaber Combat (Content Pack)
resource.AddWorkshop( '2646756503' ) -- [wOS] Animation Extension - Base  (Code Only)
resource.AddWorkshop( '757604550' ) -- [wOS] Animation Extension - Base (Full Version)
resource.AddWorkshop( '848953359' ) -- [wOS] Animation Extension - Blade Symphony
resource.AddWorkshop( '925184078' ) -- [wOS] Animation Extension - Experimental
resource.AddWorkshop( '1125980817' ) -- [wOS] Animation Extension - Riddick
resource.AddWorkshop( '2916561591' ) -- [wOS] DynaBase - Dynamic Animation Manager
resource.AddWorkshop( '2917050373' ) -- [wOS] DynaBase Legacy Extensions
resource.AddWorkshop( '2089095556' ) -- [wOS] Inquisitor Hilt Ability Extension
resource.AddWorkshop( '1799728727' ) -- [Zephyr] Imperial 501st Models Revision
resource.AddWorkshop( '1881093005' ) -- aa [SL] Anti Adware
resource.AddWorkshop( '773402917' ) -- Advanced Duplicator 2
resource.AddWorkshop( '1507107295' ) -- Alydus's Destructible Fortifications Extension
resource.AddWorkshop( '2045270509' ) -- anzatis lightsaber pack
resource.AddWorkshop( '2302156977' ) -- anzatis lightsaber pack 2
resource.AddWorkshop( '866341452' ) -- Clone Wars Adventures: Lightsabers
resource.AddWorkshop( '248302805' ) -- DarkRP
resource.AddWorkshop( '1915794658' ) -- Darth Vader  | Star Wars Battlefront 2 (PM)
resource.AddWorkshop( '1560118657' ) -- DrGBase | Nextbot Base
resource.AddWorkshop( '727905714' ) -- Enhanced Star Wars NPC Weapons
resource.AddWorkshop( '2756613495' ) -- Fortnite: Boba Fett (PM&NPC + Ragdoll)
resource.AddWorkshop( '3270800163' ) -- Fortnite: Death Trooper (PM&NPC + Ragdoll)
resource.AddWorkshop( '871426788' ) -- gExplo
resource.AddWorkshop( '2943090068' ) -- Heart Turbolaser Tool
resource.AddWorkshop( '1267236756' ) -- Helix Content
resource.AddWorkshop( '3048442007' ) -- Imperial banner
resource.AddWorkshop( '1897194135' ) -- Imperial Royal Guard (playermodels)
resource.AddWorkshop( '620565976' ) -- Inquisitor : Rebels
resource.AddWorkshop( '1333011098' ) -- Inquisitor Saber [Model]
resource.AddWorkshop( '3111031938' ) -- Luna's Flight School
resource.AddWorkshop( '3113792066' ) -- Medals - Content
resource.AddWorkshop( '546392647' ) -- Media Player
resource.AddWorkshop( '1825542758' ) -- Melee Arts 2
resource.AddWorkshop( '1080666656' ) -- Muted Toolgun
resource.AddWorkshop( '3016329665' ) -- Nada's Shared Content
resource.AddWorkshop( '2760300370' ) -- Navy Comm and RP Commands
resource.AddWorkshop( '1551310214' ) -- Placeable Particle Effects
resource.AddWorkshop( '2968431446' ) -- Police Baton
resource.AddWorkshop( '660180316' ) -- Rebel Vehicle Models
resource.AddWorkshop( '116892991' ) -- Resizer
resource.AddWorkshop( '1814414404' ) -- Revan Double Lightsaber Fix
resource.AddWorkshop( '823467265' ) -- Rogue One - A Star Wars Vehicles Addon
resource.AddWorkshop( '3452134759' ) -- rp_nevarro
resource.AddWorkshop( '284266415' ) -- Sci-fi Props Megapack
resource.AddWorkshop( '2040719439' ) -- Sovereign | Sith and Inquisitors
resource.AddWorkshop( '1206775008' ) -- Star Wars - Imperial Materials
resource.AddWorkshop( '1098229408' ) -- Star Wars - Krennic's Shuttle
resource.AddWorkshop( '946190478' ) -- Star Wars - Rogue One Prop Pack
resource.AddWorkshop( '1708099047' ) -- Star Wars - Skybox Space Props
resource.AddWorkshop( '763998519' ) -- Star Wars : Imperial Propaganda
resource.AddWorkshop( '2565724292' ) -- Star Wars : Rogue One / Mandalorian Extras
resource.AddWorkshop( '1401569450' ) -- Star Wars : Starfighters Pack [ Redux  ]
resource.AddWorkshop( '1977131704' ) -- Star Wars | Titan Imperial Base
resource.AddWorkshop( '3013414165' ) -- Star Wars || Victory 2-Class Star Destroyer
resource.AddWorkshop( '844200884' ) -- Star Wars Battlefront 2015 Sweps (REUPLOADED AND FIXED)
resource.AddWorkshop( '2518684081' ) -- Star Wars BF2 ISB Agent Playermodel
resource.AddWorkshop( '228153943' ) -- Star Wars Boba Fett Playermodel
resource.AddWorkshop( '895501418' ) -- Star Wars Capital Ships : Props Pack
resource.AddWorkshop( '909253802' ) -- Star Wars Command Posts v.2
resource.AddWorkshop( '452065494' ) -- STAR WARS Darth Vader Playermodel
resource.AddWorkshop( '1711873558' ) -- STAR WARS Electro-Binoculars Pack
resource.AddWorkshop( '457212613' ) -- STAR WARS Emperor Palpatine Playermodel
resource.AddWorkshop( '628120855' ) -- Star Wars Flags & Banners
resource.AddWorkshop( '2592925273' ) -- Star Wars HD Imperial Ship Props
resource.AddWorkshop( '111412589' ) -- Star Wars Lightsabers
resource.AddWorkshop( '671544612' ) -- Star Wars Lightsabers Extension
resource.AddWorkshop( '742660522' ) -- Star Wars Prop Pack
resource.AddWorkshop( '2710839349' ) -- Star Wars Rebel Alliance Starship NPCs
resource.AddWorkshop( '452719720' ) -- Star Wars Rebel NPC's
resource.AddWorkshop( '2935149491' ) -- STAR WARS The Clone Wars: CIS B1 & B2 Battle Droids
resource.AddWorkshop( '495762961' ) -- Star Wars Vehicles: Episode 1
resource.AddWorkshop( '608632308' ) -- Star Wars Vehicles: Episode 2
resource.AddWorkshop( '183549197' ) -- Star Wars Weapons
resource.AddWorkshop( '3005619448' ) -- Star Wars: Bossk
resource.AddWorkshop( '3005618643' ) -- Star Wars: Boushh
resource.AddWorkshop( '2971498928' ) -- Star Wars: Coruscant Security Force
resource.AddWorkshop( '2608255439' ) -- Star Wars: Death Troopers
resource.AddWorkshop( '3005620163' ) -- Star Wars: Dengar
resource.AddWorkshop( '1188200318' ) -- Star Wars: EA's Battlefront - Rebel Troopers P1 (PM & NPC)
resource.AddWorkshop( '1188211130' ) -- Star Wars: EA's Battlefront - Rebel Troopers P1 Materials
resource.AddWorkshop( '1188203210' ) -- Star Wars: EA's Battlefront - Rebel Troopers P2 (PM & NPC)
resource.AddWorkshop( '1188217028' ) -- Star Wars: EA's Battlefront - Rebel Troopers P2 Materials
resource.AddWorkshop( '2970793927' ) -- Star Wars: Empire Strikes Back Boba Fett
resource.AddWorkshop( '2918510500' ) -- Star Wars: EVO Troopers & Navy Commandos
resource.AddWorkshop( '2713428608' ) -- Star Wars: Fallen Order: ATAT Pilot (PM + Ragdoll)
resource.AddWorkshop( '2713266203' ) -- Star Wars: Fallen Order: Flametrooper (PM&NPC + Ragdoll)
resource.AddWorkshop( '3269983466' ) -- Star Wars: Fallen Order: Imperial Troopers (PM&NPC + Ragdoll)
resource.AddWorkshop( '3479481549' ) -- Star Wars: Fallen Order: KX-Series Security Droid (PM&NPC + Ragdoll)
resource.AddWorkshop( '2717283608' ) -- Star Wars: Fallen Order: Purge Trooper (PM&NPC + Ragdoll)
resource.AddWorkshop( '2714655844' ) -- Star Wars: Fallen Order: Scout Trooper (PM&NPC + Ragdoll)
resource.AddWorkshop( '2712791223' ) -- Star Wars: Fallen Order: Second Sister (PM + Ragdoll)
resource.AddWorkshop( '2718343139' ) -- Star Wars: Fallen Order: Snowtrooper (PM&NPC + Ragdoll)
resource.AddWorkshop( '2713317698' ) -- Star Wars: Fallen Order: Stormtrooper (PM&NPC + Ragdoll)
resource.AddWorkshop( '2977644380' ) -- Star Wars: Fennec Shand (Fortnite)
resource.AddWorkshop( '2977233700' ) -- Star Wars: Flame Trooper
resource.AddWorkshop( '3005620795' ) -- Star Wars: Greedo
resource.AddWorkshop( '2786837053' ) -- Star Wars: Imperial Army Troopers
resource.AddWorkshop( '2830734093' ) -- Star Wars: Imperial Combat Drivers and Cadet
resource.AddWorkshop( '2944242284' ) -- Star Wars: Imperial Commandos
resource.AddWorkshop( '2860594264' ) -- Star Wars: Imperial Factory Worker
resource.AddWorkshop( '3045798546' ) -- Star Wars: Imperial Prefab Base Props
resource.AddWorkshop( '2744564846' ) -- Star Wars: Imperial Special Forces
resource.AddWorkshop( '2620746095' ) -- Star Wars: Imperial Transport Pilot
resource.AddWorkshop( '2744247695' ) -- Star Wars: Inferno Squad
resource.AddWorkshop( '3350925147' ) -- Star Wars: ISB Director PM
resource.AddWorkshop( '2785304070' ) -- Star Wars: Lore Officers
resource.AddWorkshop( '3021867641' ) -- Star Wars: Medical Troopers
resource.AddWorkshop( '2864113048' ) -- Star Wars: Patrol Trooper
resource.AddWorkshop( '2734575432' ) -- Star Wars: Phase Zero Dark Trooper
resource.AddWorkshop( '2682634153' ) -- Star Wars: Purge Troopers
resource.AddWorkshop( '2819989158' ) -- Star Wars: Range Trooper
resource.AddWorkshop( '626826818' ) -- Star Wars: Rebel Troopers
resource.AddWorkshop( '1499527379' ) -- Star Wars: Republic Commando - Delta Squad (2018 Edition) Part 1
resource.AddWorkshop( '1499532815' ) -- Star Wars: Republic Commando - Delta Squad (2018 Edition) Part 2
resource.AddWorkshop( '1499537077' ) -- Star Wars: Republic Commando - Weapons (2018 Edition) Part 1
resource.AddWorkshop( '1499553262' ) -- Star Wars: Republic Commando - Weapons (2018 Edition) Part 2
resource.AddWorkshop( '2534420429' ) -- Star Wars: Rogue One / Mandalorian Storm Troopers
resource.AddWorkshop( '2992041971' ) -- Star Wars: Rogue One Imperial Army Officers
resource.AddWorkshop( '2992042867' ) -- Star Wars: Rogue One Imperial Goverment Officers
resource.AddWorkshop( '2992043779' ) -- Star Wars: Rogue One Imperial Misc Officers
resource.AddWorkshop( '2593940310' ) -- Star Wars: Rogue One Imperial Naval Officers
resource.AddWorkshop( '2992042480' ) -- Star Wars: Rogue One Imperial Security Officers
resource.AddWorkshop( '2725110621' ) -- Star Wars: Rogue One Jump Troopers
resource.AddWorkshop( '2593938191' ) -- Star Wars: Rogue One Tie Pilots & AT-AT Pilot
resource.AddWorkshop( '2681187758' ) -- Star Wars: Scout Troopers & Storm Commandos
resource.AddWorkshop( '3018362828' ) -- Star Wars: Scout Troopers & Storm Commandos Head Customisability
resource.AddWorkshop( '2593939207' ) -- Star Wars: Shore Troopers
resource.AddWorkshop( '2099803368' ) -- STAR WARS: Sith Inquisitors (Jedi Fallen Order)
resource.AddWorkshop( '2682627489' ) -- Star Wars: Snow Troopers & Scout
resource.AddWorkshop( '2665294503' ) -- Star Wars: Squadrons Tie Pilots
resource.AddWorkshop( '3092607242' ) -- Star Wars: Swamp Trooper
resource.AddWorkshop( '2608248069' ) -- Star Wars: Tank Troopers & AT-ACT Pilots
resource.AddWorkshop( '2764507578' ) -- Star Wars: Textscreens
resource.AddWorkshop( '2923314880' ) -- Star Wars: The Force Unleashed Royal Guards
resource.AddWorkshop( '643453713' ) -- Star Wars: The Props Awaken
resource.AddWorkshop( '2877147565' ) -- Strykers Information Panels (Imperial)
resource.AddWorkshop( '1598263759' ) -- SW Map : Deathstar
resource.AddWorkshop( '1518614446' ) -- SW Modelpack : Deathstar
resource.AddWorkshop( '938897202' ) -- SW Modelpack : Emperors Tower
resource.AddWorkshop( '1209310522' ) -- SW Modelpack : Holocrons & More
resource.AddWorkshop( '1841418570' ) -- SW Modelpack : Miscellaneous
resource.AddWorkshop( '1922420046' ) -- SW Modelpack : Skybox Props
resource.AddWorkshop( '942052283' ) -- SW Modelpack : Working Seats
resource.AddWorkshop( '1580978413' ) -- SW Shared : LFS Vehicles
resource.AddWorkshop( '2003539477' ) -- SW Shared : SWV Vehicles
resource.AddWorkshop( '1626356763' ) -- SW Vehicle : Patrol Transport
resource.AddWorkshop( '1910572465' ) -- SW Vehicle : TIE Crawler
resource.AddWorkshop( '2544011243' ) -- SW Vehicle [LFS] : AT-AT
resource.AddWorkshop( '1527897309' ) -- SW Vehicle [LFS] : TIE Defender
resource.AddWorkshop( '1322584182' ) -- SW Vehicle [LFS] : TIE Fighters
resource.AddWorkshop( '1167029588' ) -- SWTOR: Lightsaber Pack
resource.AddWorkshop( '841066734' ) -- Talk Icon
resource.AddWorkshop( '2938551981' ) -- TFA Base [Fixed Scopes]
resource.AddWorkshop( '453856288' ) -- The Defibrillator - CustomHQ Models
resource.AddWorkshop( '637501166' ) -- The Grand Inquisitor Playermodel
resource.AddWorkshop( '3353953693' ) -- Tood's Dropship Tool v2.2
resource.AddWorkshop( '1370822766' ) -- TX-225
resource.AddWorkshop( '1868459587' ) -- Vanilla's Hyperspace Tool
resource.AddWorkshop( '3049002679' ) -- Vanilla's Hyperspace Tool: LVS Edition
resource.AddWorkshop( '1885314499' ) -- Vanilla's Ship Destruction Tool
resource.AddWorkshop( '2861398079' ) -- Vibro Knife Pack